apiVersion: apps/v1
kind: Deployment
metadata:
  name: psycho-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psycho-api
  template:
    metadata:
      labels:
        app: psycho-api
    spec:
      containers:
        - name: psycho-api
          image: denchiklut/psycho-api
          env:
            - name: DEBUG
              value: 'true'
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-token
                  key: SECRET_TOKEN
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-access
                  key: DB_HOST_PROD
            - name: HOST
              value: 'https://stage.psychoschool.ru'
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL_USER
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL_PASSWORD
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: psycho-api-srv
spec:
  type: ClusterIP
  selector:
    app: psycho-api
  ports:
    - port: 8080
      targetPort: 8080
